/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_luishenriquez;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import static java.lang.System.in;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUIS HENRIQUEZ
 */
public class PRINCI extends javax.swing.JFrame {

    /**
     * Creates new form PRINCI
     */
    public PRINCI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        med = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        estatura = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        estilo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        distancia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        record = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        medallas = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        paises = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        estilos = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        dis = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        recor = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablan = new javax.swing.JTable();
        sec = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tv = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ev = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Juegos Olimpicos del 2030");

        jLabel2.setText("Nombre");

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        jLabel3.setText("Medallas obtenidas");

        jLabel4.setText("Ingresar pais");

        jButton1.setText("GUARDAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingresar nadador");

        jLabel6.setText("Nombre");

        nomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombActionPerformed(evt);
            }
        });

        jLabel7.setText("Edad");

        jLabel8.setText("Estatura");

        jLabel9.setText("Estilo");

        estilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));

        jLabel10.setText("Distancia en Metros");

        distancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800" }));

        jLabel11.setText("Record en segundos");

        jLabel12.setText("Medallas obtenidas");

        jLabel14.setText("Pais en el que participara");

        jButton2.setText("GUARDAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel15.setText("Ingresar Evento");

        estilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));
        estilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estilosActionPerformed(evt);
            }
        });

        jLabel16.setText("Estilo");

        dis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800" }));

        jLabel17.setText("Distancia en Metros");

        jLabel18.setText("Record en segundos");

        jButton3.setText("GUARDAR");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel19.setText("LISTAR JUGADORES");

        tablan.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tablan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Estatura", "Estilo", "Dsitancia", "Record", "Medallas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablan);

        jButton4.setText("LISTAR");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("LISTAR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        ev.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estilo", "Distancia", "Record"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ev);

        jLabel20.setText("LISTAR JUGADORES");

        jButton6.setText("ELIMINAR");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("ELIMINAR");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("MODIFICAR");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("MODIFICAR");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(med, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(135, 135, 135)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(estatura, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(estilo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(medallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(paises, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(estilos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(207, 207, 207)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(sec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel20))
                    .addComponent(jScrollPane2)
                    .addComponent(tv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(estilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(recor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 353, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(tv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(634, 634, 634))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        JFileChooser jfc = new JFileChooser("./");
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter(
                        "Paises", "lab");
        jfc.setFileFilter(filtro);

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;

        try {
            File fichero = null;

            fichero
                    = new File("./paisesParticipantes.lab");//./paisesParticipantes.lds

            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);

            String nombre = nom.getText();

            int medallas = Integer.parseInt(med.getValue().toString());

            pais.add(new PAISES(nombre, medallas));

            DefaultComboBoxModel modelo = (DefaultComboBoxModel) paises.getModel();

            DefaultComboBoxModel mod = (DefaultComboBoxModel) sec.getModel();

            mod.addElement(nombre);

            modelo.addElement(nombre);

            bw.writeObject(pais);

            nom.setText("");
            med.setValue(0);

            bw.flush();

            JOptionPane.showMessageDialog(this,
                    "PAISES GUARDADOS");
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void nombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        JFileChooser jfc = new JFileChooser("./");
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter(
                        "Nadadores", "Jose");
        jfc.setFileFilter(filtro);

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;

        try {
            File fichero = null;

            fichero
                    = new File("./paisesParticipantes.lab");//./paisesParticipantes.lds

            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);

            DefaultComboBoxModel modeloCB = (DefaultComboBoxModel) paises.getModel();
            int seleccion = paises.getSelectedIndex();
            String nacionalidad = modeloCB.getElementAt(seleccion).toString();

            String nombres = nomb.getText();
            nomb.setText("");

            int edads = Integer.parseInt(edad.getValue().toString());
            edad.setValue(0);

            int est = Integer.parseInt(estatura.getValue().toString());
            estatura.setValue(0);

            String estil = (String) estilo.getSelectedItem();

            int distanc = Integer.parseInt(distancia.getSelectedItem().toString());

            double rec = Double.parseDouble(record.getValue().toString());

            int medals = Integer.parseInt(medallas.getValue().toString());
            medallas.setValue(0);

            int ME = 2;
            int NE = 0;
            /*
            for (NADADORES NNE : pais.get(seleccion).getNadadores()) {
                if (NNE.getEstilo().equals(estil)) {
                    NE++;
                }
            }

            if (NE < ME) {

                nadador.add(new NADADORES(nombres, nacionalidad, edads, est, estil, distanc, rec, medals));
                pais.get(seleccion).getNadadores().add(nadador);
            } else {
                
                JOptionPane.showMessageDialog(this, "Se ha alcanzado el limite de nadadores para este estilo en este paius.");
                estil = JOptionPane.showInputDialog(this,"Ingrese el estilo nuevo");
            }
            */
            
            
            
            
            nadador.add(new NADADORES(nombres, nacionalidad, edads, est, estil, distanc, rec, medals));

            int index = paises.getSelectedIndex();

            pais.get(index).getNadadores().add(nadador);

            bw.writeObject(nadador);

            bw.flush();

            JOptionPane.showMessageDialog(this,
                    "Nadadores GUARDADOS");
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }


    }//GEN-LAST:event_jButton2MouseClicked

    private void estilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estilosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estilosActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        JFileChooser jfc = new JFileChooser("./");
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter(
                        "Eventos", "pov");
        jfc.setFileFilter(filtro);

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;

        try {
            File fichero = null;

            fichero
                    = new File("./paisesParticipantes.lab");//./paisesParticipantes.lds

            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);

            String estiloo = (String) estilos.getSelectedItem();

            int diss = Integer.parseInt(dis.getSelectedItem().toString());

            double recoo = Double.parseDouble(recor.getValue().toString());

            evento.add(new EVENTOS(estiloo, diss, recoo));

            DefaultComboBoxModel mod = (DefaultComboBoxModel) tv.getModel();

            String simon = "Evento #" + conta;

            mod.addElement(simon);

            conta++;
            bw.writeObject(evento);

            bw.flush();

            JOptionPane.showMessageDialog(this,
                    "Eventos GUARDADOS");
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        /*
        int index = sec.getSelectedIndex();
             Object[] row;
        for(int i = 0; i < pais.get(index).getNadadores().size(); i++){
            
            NADADORES n = (NADADORES) pais.get(index).getNadadores().get(i);
            row = {n.getNombre(),n.getEdad()};
        }
        
       
       
       DefaultTableModel modelo
                = (DefaultTableModel) tablan.getModel();

        modelo.addRow(row);
        tablan.setModel(modelo);
         */
        int ok = sec.getSelectedIndex();
        DefaultTableModel modelo = (DefaultTableModel) tablan.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        DefaultComboBoxModel modeloCB = (DefaultComboBoxModel) sec.getModel();
        String paisSeleccionado = modeloCB.getElementAt(ok).toString();
        for (NADADORES n : nadador) {
            if (n.getNacionalidad().equals(paisSeleccionado)) {
                Object[] row = new Object[7];
                row[0] = n.getNombre();
                row[1] = n.getEdad();
                row[2] = n.getEstatura();
                row[3] = n.getEstilo();
                row[4] = n.getDistancia();
                row[5] = n.getRecord();
                row[6] = n.getMedallas();
                modelo.addRow(row);
            }
        }

        tablan.setModel(modelo);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        DefaultTableModel modelo = (DefaultTableModel) ev.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        for (EVENTOS n : evento) {

            Object[] row = new Object[3];
            row[0] = n.getEstilo();
            row[1] = n.getDistancia();
            row[2] = n.getRecord();

            modelo.addRow(row);

        }

        ev.setModel(modelo);

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tablan.getModel();
        String input = JOptionPane.showInputDialog(this, "Ingrese el numero a eliminar:");
        if (input != null && !input.isEmpty()) {
            try {
                int el = Integer.parseInt(input);
                if (el >= 0 && el < modelo.getRowCount()) {

                    nadador.remove(el);
                    modelo.removeRow(el);
                } else {
                    JOptionPane.showMessageDialog(this, "Numero de fila no valido.");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "INVALIDO");
            }
        }


    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) ev.getModel();
        String input = JOptionPane.showInputDialog(this, "Ingrese el numero a eliminar:");
        if (input != null && !input.isEmpty()) {

            int el = Integer.parseInt(input);
            if (el >= 0 && el < modelo.getRowCount()) {

                evento.remove(el);
                modelo.removeRow(el);
            } else {
                JOptionPane.showMessageDialog(this, "Numero de fila no valido.");
            }
        }

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) ev.getModel();
        String SI = JOptionPane.showInputDialog(this, "Ingrese el numero de fila a modificar:");
        if (SI != null && !SI.isEmpty()) {

            int mod = Integer.parseInt(SI);
            if (mod >= 0 && mod < modelo.getRowCount()) {

                String NE = JOptionPane.showInputDialog(this, "Ingrese el nuevo estilo:");
                String ND = JOptionPane.showInputDialog(this, "Ingrese la nueva distancia:");
                String NR = JOptionPane.showInputDialog(this, "Ingrese el nuevo recorrido:");

                int NND = Integer.parseInt(ND);
                double NNR = Double.parseDouble(NR);

                EVENTOS eventoModificado = evento.get(mod);
                eventoModificado.setEstilo(NE);
                eventoModificado.setDistancia(NND);
                eventoModificado.setRecord(NNR);

                modelo.setValueAt(NE, mod, 0);
                modelo.setValueAt(NND, mod, 1);
                modelo.setValueAt(NNR, mod, 2);
            } else {
                JOptionPane.showMessageDialog(this, "Numero de fila no valido.");
            }

        }

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tablan.getModel();
        String SI = JOptionPane.showInputDialog(this, "Ingrese el numero de fila a modificar:");
        if (SI != null && !SI.isEmpty()) {

            int mod = Integer.parseInt(SI);
            if (mod >= 0 && mod < modelo.getRowCount()) {
                String NE = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre:");
                String NED = JOptionPane.showInputDialog(this, "Ingrese la nueva edad:");
                String NEst = JOptionPane.showInputDialog(this, "Ingrese la nueva estatura:");
                String NEstilo = JOptionPane.showInputDialog(this, "Ingrese el nuevo estilo:");
                String NDistancia = JOptionPane.showInputDialog(this, "Ingrese la nueva distancia:");
                String NRecorrido = JOptionPane.showInputDialog(this, "Ingrese el nuevo recorrido:");
                String NMedallas = JOptionPane.showInputDialog(this, "Ingrese la nueva cantidad de medallas:");

                int NEdad = Integer.parseInt(NED);
                int NEstatura = Integer.parseInt(NEst);
                int NDist = Integer.parseInt(NDistancia);
                double NRec = Double.parseDouble(NRecorrido);
                int NMed = Integer.parseInt(NMedallas);

                NADADORES nadadorModificado = nadador.get(mod);
                nadadorModificado.setNombre(NE);
                nadadorModificado.setEdad(NEdad);
                nadadorModificado.setEstatura(NEstatura);
                nadadorModificado.setEstilo(NEstilo);
                nadadorModificado.setDistancia(NDist);
                nadadorModificado.setRecord(NRec);
                nadadorModificado.setMedallas(NMed);

                modelo.setValueAt(NE, mod, 0);
                modelo.setValueAt(NEdad, mod, 1);
                modelo.setValueAt(NEstatura, mod, 2);
                modelo.setValueAt(NEstilo, mod, 3);
                modelo.setValueAt(NDist, mod, 4);
                modelo.setValueAt(NRec, mod, 5);
                modelo.setValueAt(NMed, mod, 6);
            } else {
                JOptionPane.showMessageDialog(this, "INVALIDO");
            }

        }
    }//GEN-LAST:event_jButton9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dis;
    private javax.swing.JComboBox<String> distancia;
    private javax.swing.JSpinner edad;
    private javax.swing.JSpinner estatura;
    private javax.swing.JComboBox<String> estilo;
    private javax.swing.JComboBox<String> estilos;
    private javax.swing.JTable ev;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner med;
    private javax.swing.JSpinner medallas;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomb;
    private javax.swing.JComboBox<String> paises;
    private javax.swing.JSpinner recor;
    private javax.swing.JSpinner record;
    private javax.swing.JComboBox<String> sec;
    private javax.swing.JTable tablan;
    private javax.swing.JComboBox<String> tv;
    // End of variables declaration//GEN-END:variables
ArrayList<PAISES> pais = new ArrayList<>();
    ArrayList<NADADORES> nadador = new ArrayList<>();
    ArrayList<EVENTOS> evento = new ArrayList<>();
    int conta = 1;
}
